server:
  port: 5000


spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/cafein
    username: sa
    password:
    driver-class-name: org.h2.Driver

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 30e9f4fa92d2521d41eaf6f419dd5185
            redirect-uri: http://localhost:5000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao

          naver:
            client-id: ybDKeWgTb42oM50zK5Q7
            client-secret: kwn3jI4fwx
            redirect-uri: http://localhost:5000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response


app:
  token:
    secretKey: 1234rhjknsdkjn2kKJnfkjanhdsfkjsdnaflkasjfnksjdfnksjdfs478415616
  oauth2:
    authorized-redirect-url: http://localhost:55773