server:
  port: 5000

spring:
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000
    open-in-view: false
    show-sql: true

  servlet:
    multipart:
      max-file-size: 2MB

coolsms:
  fromNumber : 070-8065-0427

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error