server:
  port: 5000

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/cafein
    username: sa
    password:
    driver-class-name: org.h2.Driver

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000
    open-in-view: false
    show-sql: true

  servlet:
    multipart:
      max-file-size: 2MB

app:
  token:
    secretKey: 1234rhjknsdkjn2kKJnfkjanhdsfkjsdnaflkasjfnksjdfnksjdfs478415616

apple:


coolsms:


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    credentials:

    s3:
      bucket: cafein-bucket # prod 버전
    region:
      static: ap-northeast-2
    stack:
      auto: false

dataSet:
  naver:
    clientId: dOXazpqK7gPsCGdr9Bou
    clientSecret: onJyZriJJg
  kakao:
    apiKey: 30e9f4fa92d2521d41eaf6f419dd5185
  google:
    apiKey: AIzaSyBDI-wlA5X_j_kDC4f8TX1ENLiJ-uI5otI
  naverCloud:
    clientId: 0e5xej9tyd
    clientSecret: xxq1flvQyEuQQJNygzZhx53OQcmH7cTE6zeSk6Pm