server:
  port: 5000

spring:
  datasource:
    url: ${REALSE_DATABASE_URL}
    username: ${REALSE_DATABASE_USERNAME}
    password: ${REALSE_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REALSE_REDIS_SERVER}
    port: 6379


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000
    open-in-view: false
    show-sql: true

  servlet:
    multipart:
      max-file-size: 2MB

app:
  token:
    secretKey: ${REALSE_JWT_SECRET_KEY}

apple:
  keyId : ${REALSE_APPLE_KEY_ID}
  clientId : ${REALSE_APPLE_CLIENT_ID}
  teamId : ${REALSE_APPLE_TEAM_ID}

coolsms:
  apiKey : ${REALSE_COOLSMS_API_KEY}
  apiSecret: ${REALSE_COOLSMS_API_SECRET}
  fromNumber : 070-8065-0427

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    credentials:
      accessKey: ${REALSE_AWS_ACCESS_KEY_ID}
      secretKey: ${REALSE_AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${REALSE_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false

dataSet:
  naver:
    clientId: ${REALSE_NAVER_CLIENT_ID}
    clientSecret: ${REALSE_NAVER_CLIENT_SECRET}
  kakao:
    apiKey: ${REALSE_KAKAO_API_KEY}
  google:
    apiKey: ${REALSE_GOOGLE_API_KEY}
  naverCloud:
    clientId: ${REALSE_NAVER_CLOUD_CLIENT_ID}
    clientSecret: ${REALSE_NAVER_CLOUD_CLIENT_SECRET}
